import React, {useState} from 'react';
import {Eye, Plus, Search, Package, TrendingUp, MapPin} from 'lucide-react';
import {useWorkspaceUI} from '../context/WorkspaceUIContext';
import type {Order,Member} from './api';
const money=(n:number,c:string)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format(n/100);

// Original OrdersView presentation adapted to server records only. No delivery,
// distributor, cash, delete or inventory handlers are imported from the demo.
export function OrdersTable({orders,members,onCreate,renderDetails}:{orders:Order[];members:Member[];onCreate:()=>void;renderDetails:(order:Order)=>React.ReactNode}) {
 const {themeMode}=useWorkspaceUI();const isLight=themeMode==='light';
 const [search,setSearch]=useState(''),[status,setStatus]=useState('ALL'),[selected,setSelected]=useState<string|null>(null);
 const surface=isLight?'bg-white border-slate-200':'bg-slate-900/60 border-slate-800';
 const filtered=orders.filter(o=>(status==='ALL'||status===o.status)&&[o.orderNumber,o.customerName,o.customerPhone,o.deliveryCity,o.deliveryState].join(' ').toLowerCase().includes(search.toLowerCase()));
 const selectedOrder=orders.find(o=>o.id===selected);
 return <div className="space-y-6">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-xl sm:text-2xl font-bold tracking-tight">Orders Management</h1><p className="text-xs sm:text-sm text-slate-400">Track and manage your assigned customer orders in real-time</p></div><button onClick={onCreate} className="flex items-center gap-1.5 px-3.5 py-1.5 rounded-lg bg-emerald-600 text-xs font-semibold text-white shadow-sm"><Plus className="w-3.5 h-3.5"/>Create Order</button></div>
  <div className="grid grid-cols-2 lg:grid-cols-4 gap-3">{[['Total Orders',orders.length],['New Orders',orders.filter(o=>o.status==='NEW').length],['Confirmed',orders.filter(o=>o.status==='CONFIRMED').length],['Scheduled',orders.filter(o=>o.status==='SCHEDULED').length]].map(([label,value])=><div key={label} className={`rounded-xl border p-4 space-y-2 ${surface}`}><p className="text-xs text-slate-400">{label}</p><p className="text-2xl font-bold font-mono">{value}</p></div>)}</div>
  <div className="space-y-3">{[{title:'Orders Revenue Opportunity',icon:TrendingUp,content:<p className="text-xs text-slate-400">Order values are shown in the ledger below. Collections, revenue recognition and financial reporting are not enabled in this milestone.</p>},{title:'New Orders by Product',icon:Package,content:<ul className="text-xs space-y-2">{Array.from(new Set(orders.filter(o=>o.status==='NEW').flatMap(o=>o.items.map(i=>i.productName)))).map(name=><li key={name}>{name} · {orders.filter(o=>o.status==='NEW'&&o.items.some(i=>i.productName===name)).length} orders</li>)}{!orders.some(o=>o.status==='NEW')&&<li>No new orders.</li>}</ul>},{title:'Top States',icon:MapPin,content:<ul className="text-xs space-y-2">{Array.from(new Set(orders.map(o=>o.deliveryState))).map(state=><li key={state}>{state} · {orders.filter(o=>o.deliveryState===state).length} orders</li>)}{!orders.length&&<li>No order locations yet.</li>}</ul>}].map(({title,icon:Icon,content})=><details key={title} className={`rounded-xl border overflow-hidden shadow-sm ${surface}`}><summary className="px-4 sm:px-5 py-3.5 cursor-pointer text-xs sm:text-sm font-bold"><Icon className="w-4 h-4 text-emerald-400 inline mr-2.5"/>{title}</summary><div className="p-4 border-t border-slate-800">{content}</div></details>)}</div>
  <div className={`rounded-xl border p-3 flex flex-col sm:flex-row gap-3 ${surface}`}><label className="relative flex-1"><span className="sr-only">Search orders</span><Search className="absolute w-4 h-4 left-3 top-2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search by order ID, customer, phone or location…" className="w-full rounded-lg pl-9 pr-3 py-1.5 text-xs border border-slate-800 bg-slate-950"/></label><label><span className="sr-only">Filter status</span><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-lg px-2.5 py-1.5 text-xs border border-slate-800 bg-slate-950"><option value="ALL">All Statuses</option>{Array.from(new Set(['NEW','CONFIRMED','SCHEDULED',...orders.map(o=>o.status)])).map(s=><option key={s}>{s}</option>)}</select></label></div>
  <div className={`rounded-2xl border overflow-hidden shadow-sm ${surface}`}><div className="overflow-x-auto"><table aria-label="Orders" className="w-full text-left text-xs"><thead><tr className={`border-b text-[11px] font-semibold ${isLight?'bg-slate-50 border-slate-200 text-slate-700':'bg-slate-950/90 border-slate-800 text-slate-400'}`}>{['Order ID','Customer Name','Status','Sales Rep','Location','Total','Actions'].map(h=><th key={h} className="py-3 px-3 font-semibold whitespace-nowrap">{h}</th>)}</tr></thead><tbody className={`divide-y ${isLight?'divide-slate-100':'divide-slate-800/50'}`}>{filtered.map(o=><tr key={o.id} className={isLight?'hover:bg-slate-50/80':'hover:bg-slate-800/40'}><td className="py-3 px-3 font-mono font-bold text-emerald-400 whitespace-nowrap">{o.orderNumber}</td><td className="py-3 px-3 whitespace-nowrap"><p className="font-bold text-xs">{o.customerName}</p><p className="text-[10px] font-mono text-slate-400">{o.customerPhone}</p></td><td className="py-3 px-3"><span className="px-2.5 py-0.5 rounded-full text-[10px] font-mono font-bold border border-amber-700 text-amber-300 bg-amber-950/40">{o.status}</span></td><td className="py-3 px-3 whitespace-nowrap">{o.assignedUserId?(members.find(m=>m.user_id===o.assignedUserId)?.full_name??'Assigned'):'Unassigned'}</td><td className="py-3 px-3 whitespace-nowrap">{o.deliveryCity}, {o.deliveryState}</td><td className="py-3 px-3 font-mono font-bold whitespace-nowrap">{money(o.totalMinor,o.currency)}</td><td className="py-3 px-3"><button aria-label={`View order ${o.orderNumber}`} onClick={()=>setSelected(selected===o.id?null:o.id)} className="p-1.5 rounded-lg border border-slate-700 text-slate-300"><Eye className="w-3.5 h-3.5"/></button></td></tr>)}{!filtered.length&&<tr><td colSpan={7} className="py-12 px-4 text-center text-slate-400">{orders.length?'No orders match your filter criteria.':'No orders yet. Publish an order form or create an order.'}</td></tr>}</tbody></table></div></div>
  {selectedOrder&&<section aria-label="Order details" className="space-y-3"><button onClick={()=>setSelected(null)} className="text-xs text-slate-400">Close details</button>{renderDetails(selectedOrder)}</section>}
 </div>;
}
