import React, { useEffect, useState } from 'react';
import { useAuth } from '../context/AuthContext';
import {OrdersTable} from './OrdersTable';
import {useWorkspaceUI} from '../context/WorkspaceUIContext';
import { request, submissionKey, orderPayload, Product, Order, Member } from './api';
const box='rounded-xl border border-white/10 bg-slate-900/70 p-5 space-y-4';
const input='block w-full mt-1 p-2 rounded-lg border border-slate-600 bg-slate-950 text-white';
const button='px-4 py-2 rounded-lg bg-emerald-500 text-black font-semibold disabled:opacity-40';
const money=(n:number,c:string)=>new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format(n/100);
function Field({name,label,type='text',required=true,defaultValue}: {name:string;label:string;type?:string;required?:boolean;defaultValue?:string|number}){return <label className="block text-sm text-slate-300">{label}<input className={input} name={name} type={type} required={required} defaultValue={defaultValue} min={type==='number'?1:undefined}/></label>}
function Intake({products,path,scope,token,onSaved,publicForm=false}: {products:Product[];path:string;scope:string;token?:string;onSaved?:(o:Order)=>void;publicForm?:boolean}){
 const [error,setError]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState<Order|null>(null);
 const pending=sessionStorage.getItem(`bettatraka:pending:${scope}`);
 let draft:any={};try{draft=pending?JSON.parse(JSON.parse(pending).fingerprint):{}}catch{}
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');
 try{const fields=Object.fromEntries(new FormData(e.currentTarget)); const body=orderPayload({...fields,quantity:Number(fields.quantity)}); const key=submissionKey(sessionStorage,scope,body);
 const result=await request(path,{method:'POST',headers:{'Idempotency-Key':key},body:JSON.stringify(body)},token);setSaved(result.order);sessionStorage.removeItem(`bettatraka:pending:${scope}`);onSaved?.(result.order);
 }catch(e:any){if(e.status===400)sessionStorage.removeItem(`bettatraka:pending:${scope}`);setError(e.message)}finally{setBusy(false)}}
 if(saved)return <div role="status" className={box}><h2 className="text-xl text-emerald-400">Order received</h2><p>Reference: {saved.orderNumber}</p><p>{money(saved.totalMinor,saved.currency)}{!publicForm&&` · ${saved.status}`}</p><button className={button} onClick={()=>setSaved(null)}>Start another order</button></div>;
 return <form className={box} onSubmit={submit}><fieldset disabled={busy} className="space-y-4">{publicForm&&<section className="space-y-3"><h2 className="font-mono text-[11px] uppercase tracking-wider text-emerald-400 font-bold">Step 1: Select Your Package Bundle</h2>{products.filter(p=>p.active).flatMap(p=>p.packages.map(k=><label key={k.id} className="flex items-center justify-between gap-3 p-4 rounded-xl border border-slate-800 bg-slate-950/60 cursor-pointer has-[:checked]:border-emerald-500 has-[:checked]:bg-emerald-950/20 has-[:checked]:ring-1 has-[:checked]:ring-emerald-500/50"><span className="flex items-center gap-2.5"><input type="radio" name="packageId" required value={k.id} defaultChecked={draft.packageId===k.id}/><span><span className="block font-semibold text-white text-xs">{p.name} — {k.name}</span><span className="text-[11px] text-slate-400">{k.quantity} units</span></span></span><span className="font-mono font-bold text-sm">{money(k.priceMinor,p.currency)}</span></label>))}</section>}{publicForm&&<h2 className="font-mono text-[11px] uppercase tracking-wider text-emerald-400 font-bold">Step 2: Where Should We Deliver Your Package?</h2>}<div className="grid sm:grid-cols-2 gap-4">{[['customerName','Customer name'],['customerPhone','Phone'],['alternatePhone','Alternate phone'],['customerEmail','Email'],['deliveryAddress','Delivery address'],['deliveryCity','City'],['deliveryState','State'],['notes','Notes']].map(([name,label])=><Field key={name} name={name} label={label} required={!['alternatePhone','customerEmail','notes'].includes(name)} type={name==='customerEmail'?'email':'text'} defaultValue={draft[name]}/>)}</div>
 {!publicForm&&<label className="block">Package<select name="packageId" className={input} required defaultValue={draft.packageId??''}><option value="">Choose a package</option>{products.filter(p=>p.active).flatMap(p=>p.packages.map(k=><option key={k.id} value={k.id}>{p.name} — {k.name} ({k.quantity} units) — {money(k.priceMinor,p.currency)}</option>))}</select></label>}<Field name="quantity" label="Number of packages" type="number" defaultValue={draft.quantity??1}/><button className={button} disabled={!products.length||busy}>{busy?'Submitting…':'Submit order'}</button></fieldset>{error&&<p role="alert" className="text-rose-400">{error}</p>}</form>
}
export function PublicIntake({slug}:{slug:string}){
 const [data,setData]=useState<any>(null),[error,setError]=useState('');
 useEffect(()=>{let live=true;request('/api/public/forms/'+slug).then(d=>{if(live)setData(d)}).catch(e=>{if(live)setError(e.message)});return()=>{live=false}},[slug]);
 return <main className="min-h-screen bg-slate-950 text-white p-4 sm:p-6"><div className="max-w-xl mx-auto rounded-2xl border border-slate-800 bg-slate-900/90 shadow-2xl p-4 sm:p-6 lg:p-8 space-y-6"><h1 className="text-xl lg:text-2xl text-center font-bold uppercase border-b border-slate-800 pb-4">{data?.form.title??'Order form'}</h1>{error?<p role="alert">{error}</p>:data?<Intake publicForm products={data.products} path={`/api/public/forms/${slug}/orders`} scope={'public:'+slug}/>:<p>Loading form…</p>}</div></main>
}
export function SharedWorkspace(){
 const {role,activeOrganization,user}=useAuth(); const token=localStorage.getItem('bettatraka_token')??undefined;
 const manager=['Owner','Admin','Manager'].includes(role??'');
 const {adminActiveTab,setAdminActiveTab}=useWorkspaceUI();
 const titles:Record<string,string>={orders:'Orders','new-order':'New order',products:'Products','embed-forms':'Order forms','financial-reports':'Finance & Accounting'};
 const tab=titles[adminActiveTab]??adminActiveTab;
 const [orders,setOrders]=useState<Order[]>([]),[products,setProducts]=useState<Product[]>([]),[forms,setForms]=useState<any[]>([]),[members,setMembers]=useState<Member[]>([]),[error,setError]=useState(''),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false);
 const allowed=manager||role==='Sales Representative';
 async function load(){setLoading(true);setError('');try{const [o,p,f,m]=await Promise.all([request('/api/orders',{},token),request('/api/catalog/products',{},token),manager?request('/api/order-forms',{},token):{forms:[]},manager?request('/api/organizations/members',{},token):{members:[]}]);setOrders(o.orders);setProducts(p.products);setForms(f.forms);setMembers(m.members)}catch(e:any){setOrders([]);setProducts([]);setForms([]);setMembers([]);setError(e.message)}finally{setLoading(false)}}
 useEffect(()=>{if(allowed)void load();else setLoading(false)},[]);
 async function mutate(path:string,body:any,method='POST'){setBusy(true);setError('');try{await request(path,{method,body:JSON.stringify(body)},token);await load()}catch(e:any){setError(e.message)}finally{setBusy(false)}}
 return <div className="p-4 sm:p-6 space-y-5 max-w-[1600px] mx-auto"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl font-bold tracking-tight">{tab}</h2><p className="text-xs text-slate-400 mt-1">{role==='Sales Representative'?'Your assigned orders':'Shared workspace'} · {activeOrganization?.name}</p></div><button className="px-3 py-1.5 rounded-lg border border-slate-700 text-xs font-semibold" disabled={!allowed||loading||busy} onClick={()=>load()}>Refresh</button></div>{error&&<p role="alert" className="text-rose-400">{error}</p>}
 {!allowed?<div className={box}><h3>Not available in this milestone</h3><p>Your role does not have access to shared orders. This module has no enabled actions.</p></div>:loading?<p>Loading shared records…</p>:<>
 {tab==='Orders'&&!error&&<OrdersTable orders={orders} members={members} onCreate={()=>setAdminActiveTab('new-order')} renderDetails={o=><OrderCard key={o.id+o.status+o.assignedUserId+o.notes+o.scheduledDate} order={o} members={members} manager={manager} busy={busy} save={b=>mutate('/api/orders/'+o.id,b,'PATCH')}/>}/>}
 {tab==='New order'&&<Intake products={products} path="/api/orders" scope={`manual:${activeOrganization?.id}:${user?.id}`} token={token} onSaved={o=>setOrders(current=>[o,...current.filter(existing=>existing.id!==o.id)])}/>}
 {tab==='Products'&&manager&&<><form className={box} onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));void mutate('/api/catalog/products',{name:f.name,sku:f.sku,currency:f.currency,active:true,packages:[{name:f.packageName,quantity:Number(f.units),priceMinor:Number(f.price)}]})}}><h3>Create product & package</h3><Field name="name" label="Product name"/><Field name="sku" label="SKU"/><Field name="currency" label="Currency (ISO code)" defaultValue="NGN"/><Field name="packageName" label="Package name"/><Field name="units" label="Units per package" type="number" defaultValue={1}/><label>Price in minor units (100 = 1 currency unit)<input name="price" type="number" min="0" step="1" required className={input}/></label><button disabled={busy} className={button}>Save product</button></form>{products.map(p=><div className={box} key={p.id}><h3>{p.name} · {p.sku}</h3>{p.packages.map(k=><p key={k.id}>{k.name}: {k.quantity} units · {money(k.priceMinor,p.currency)}</p>)}</div>)}</>}
 {tab==='Order forms'&&manager&&<><form className={box} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void mutate('/api/order-forms',{title:f.get('title'),slug:f.get('slug'),productIds:f.getAll('productIds'),published:f.get('published')==='on'})}}><Field name="title" label="Form title"/><Field name="slug" label="Public slug (lowercase letters, numbers, hyphens)"/>{products.filter(p=>p.active).map(p=><label className="block" key={p.id}><input name="productIds" type="checkbox" value={p.id}/> {p.name}</label>)}<label className="block"><input name="published" type="checkbox" defaultChecked/> Published</label><button className={button} disabled={busy||!products.length}>Create form</button></form>{forms.map(f=><div className={box} key={f.id}><h3>{f.title}</h3>{f.published?<a className="text-emerald-400 underline" href={'/order-form/'+f.slug} target="_blank" rel="noreferrer">/order-form/{f.slug}</a>:<p>Draft — not public</p>}</div>)}</>}
 {!['Orders','New order','Products','Order forms'].includes(tab)&&<div className={box}><h3>Not available in this milestone</h3><p className="text-slate-400">{tab} is not migrated. Demo mutations are disabled. No delivery, inventory, cash or financial effects are performed.</p></div>}
 </>}</div>
}
function OrderCard({order:o,members,manager,busy,save}:{order:Order;members:Member[];manager:boolean;busy:boolean;save:(b:any)=>void}){
 return <article className={box}><div className="flex justify-between gap-4"><h3 className="font-bold">{o.customerName}</h3><span className="text-emerald-400">{money(o.totalMinor,o.currency)} · {o.status}</span></div><p className="text-xs text-slate-500">{o.orderNumber} · {new Date(o.createdAt).toLocaleString()}</p><p>{o.customerPhone} {o.alternatePhone} {o.customerEmail}</p><p>{o.deliveryAddress}, {o.deliveryCity}, {o.deliveryState}</p>{o.items.map((i,n)=><p key={n}>{i.productName} — {i.packageName}: {i.quantity} packages × {i.packageQuantity} units</p>)}<form className="grid sm:grid-cols-2 gap-4" onSubmit={e=>{e.preventDefault();const f=Object.fromEntries(new FormData(e.currentTarget));save({...f,scheduledDate:f.scheduledDate||null,...(manager?{assignedUserId:f.assignedUserId||null}:{})})}}><label>Status<select name="status" className={input} defaultValue={o.status}>{['NEW','CONFIRMED','SCHEDULED'].map(s=><option key={s}>{s}</option>)}</select></label><Field name="scheduledDate" label="Scheduled date" type="date" required={false} defaultValue={o.scheduledDate??''}/>{manager&&<label>Assigned staff<select name="assignedUserId" className={input} defaultValue={o.assignedUserId??''}><option value="">Unassigned</option>{members.filter(m=>m.status==='ACTIVE'&&['Owner','Admin','Manager','Sales Representative'].includes(m.role)).map(m=><option key={m.user_id} value={m.user_id}>{m.full_name} ({m.role})</option>)}</select></label>}<Field name="notes" label="Notes" required={false} defaultValue={o.notes??''}/><button className={button} disabled={busy}>Save order</button></form></article>
}
